version: "3.7"
services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_kimetene
      MYSQL_DATABASE: streaming_tv
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password_kimetene
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 7090:80
